### ISSUE TITLE
User can view a list of champions.

### ISSUE THREAD

**Issue by jayhpark99** [jayhpark99/ajax-project#1]
## 📐 Functionality

> ##### User can scroll through a gallery of champion cards and see their picture.

## ✅ Task List

> ##### 

- [x] there is a fixed header with the title
- [x] displays each champion in a card with their name
- [x] styling
- [x] ensure device is mobile/desktop responsive
